using System.Net;
using System.Text;
using System.Text.Json;
using SelfService.Tagging;
using SelfService.Portal;
using Xunit;

namespace SelfService.Portal.Tests;

public sealed class TaggingTests
{
    const string Sub="11111111-1111-1111-1111-111111111111", Tenant="22222222-2222-2222-2222-222222222222";
    const string Id="/subscriptions/"+Sub+"/resourcegroups/test/providers/microsoft.storage/storageaccounts/test";
    static TagProfile Profile()=>new(){SubscriptionId=Sub,TenantId=Tenant,ExternalResourceIds=[Id],QualifiedWriteTypes=["microsoft.storage/storageaccounts"]};
    static TagInventory Inventory(TagProfile? p=null,Dictionary<string,string>? tags=null)=>TagRules.Seal(new("platform.tag-inventory/v1","fixture",Tenant,Sub,"Test fixture",DateTimeOffset.UtcNow,[TagRules.Resource(Id,"test","microsoft.storage/storageaccounts","test","eastus",tags??new(),p??Profile())],new[]{"Resources","ResourceGroups","SubscriptionTags","Governance"}.Select(n=>new TagCoverage(n,"Succeeded",1,"fixture")).ToArray(),"governance",""));
    static TagRequest Request(TagInventory i,string key="custom.team",string value="Example",string op="AddIfAbsent")=>new("platform.tag-change-request/v1",i.Digest,[new(Id,key,value,op)]);
    [Fact] public void UnownedInventoryCannotGrantOwnership(){var p=Profile() with{ExternalResourceIds=[]};var i=Inventory(p);var plan=TagRules.BuildPlan(i,Request(i),p,DateTimeOffset.UtcNow);Assert.Contains(plan.Blockers,x=>x.Contains("ownership"));var forged=TagRules.Seal(i with{Resources=[i.Resources[0] with{Ownership="External"}]});Assert.Throws<TagException>(()=>TagRules.ValidateInventory(forged,p));}
    [Fact] public void MarkerRestrictsExplicitExternalRegistration(){var i=Inventory(tags:new(){{"managedBy","Bicep"}});Assert.Equal("Unknown",i.Resources[0].Ownership);}
    [Fact] public void CustomMergePreservesCaseAndExistingValues(){var i=Inventory(tags:new(){{"Custom.Team","Existing"},{"unrelated","keep"}});var plan=TagRules.BuildPlan(i,Request(i),Profile(),DateTimeOffset.UtcNow);Assert.Empty(plan.Blockers);Assert.Equal("NoChange",plan.Changes[0].Action);Assert.Equal("Existing",plan.Changes[0].Value);Assert.Equal("Custom.Team",plan.Changes[0].Key);}
    [Fact] public void SourceOwnershipCannotBeDirectlyApplied(){var p=Profile() with{SourceTargets=new(){{Id,"self-service/targets/storage.dev.json"}}};var i=Inventory(p);var plan=TagRules.BuildPlan(i,Request(i),p,DateTimeOffset.UtcNow);Assert.Equal("SourceChange",plan.Changes[0].Route);Assert.Throws<TagException>(()=>TagRules.ValidatePlan(plan,p,DateTimeOffset.UtcNow));}
    [Theory][InlineData("managedBy","x")][InlineData("hidden-state","x")][InlineData("custom.secret","x")][InlineData("custom.team","Bearer abc")][InlineData("owner","person@example.com")][InlineData("bad/key","x")][InlineData("unknown","x")]
    public void InvalidProtectedOrSensitiveDraftsAreRejected(string key,string value){var i=Inventory();Assert.Throws<TagException>(()=>TagRules.BuildPlan(i,Request(i,key,value),Profile(),DateTimeOffset.UtcNow));}
    [Fact] public void SensitiveObservationIsMaskedAndBlocks(){var i=Inventory(tags:new(){{"owner","person@example.com"}});Assert.Equal(TagRules.Mask,i.Resources[0].Tags["owner"]);Assert.DoesNotContain("person@",TagJson.Write(i));TagRules.ValidateInventory(i,Profile());Assert.Contains(TagRules.BuildPlan(i,Request(i),Profile(),DateTimeOffset.UtcNow).Blockers,x=>x.Contains("masked"));}
    [Fact] public void DuplicateKeysAndScopeEscapesFailClosed(){Assert.Throws<TagException>(()=>TagJson.Read<TagProfile>("{\"id\":\"a\",\"Id\":\"b\"}"));Assert.Throws<TagException>(()=>TagRules.Id(Id.Replace(Sub,Tenant),Sub));var i=Inventory();Assert.Throws<TagException>(()=>TagRules.BuildPlan(i,Request(i) with{Edits=[new(Id,"custom.team","a","SetValue"),new(Id,"CUSTOM.TEAM","b","SetValue")]},Profile(),DateTimeOffset.UtcNow));}
    [Fact] public void PartialAndMissingCoverageCannotAuthorize(){foreach(var coverage in new[]{Array.Empty<TagCoverage>(),Inventory().Coverage.Select(c=>c with{State="Partial"}).ToArray()}){var i=TagRules.Seal(Inventory() with{Coverage=coverage});Assert.NotEmpty(TagRules.BuildPlan(i,Request(i),Profile(),DateTimeOffset.UtcNow).Blockers);}}
    [Fact] public void StaleEvidenceAndUnknownTypesBlock(){var i=TagRules.Seal(Inventory() with{ObservedUtc=DateTimeOffset.UtcNow.AddHours(-1)});Assert.NotEmpty(TagRules.BuildPlan(i,Request(i),Profile(),DateTimeOffset.UtcNow).Blockers);var p=Profile() with{QualifiedWriteTypes=[]};i=Inventory(p);Assert.NotEmpty(TagRules.BuildPlan(i,Request(i),p,DateTimeOffset.UtcNow).Blockers);}
    [Fact] public void LimitAndUnknownOperationRejected(){var i=Inventory();Assert.Throws<TagException>(()=>TagRules.BuildPlan(i,Request(i,value:new string('x',257)),Profile(),DateTimeOffset.UtcNow));Assert.Throws<TagException>(()=>TagRules.BuildPlan(i,Request(i,op:"Delete"),Profile(),DateTimeOffset.UtcNow));}
    [Fact] public void RehashedTamperedPlanCannotChangeUserIntent(){var i=Inventory();var p=TagRules.BuildPlan(i,Request(i),Profile(),DateTimeOffset.UtcNow);p=p with{Changes=[p.Changes[0] with{Value="Changed"}]};p=p with{Digest=TagRules.PlanHash(p)};Assert.Throws<TagException>(()=>TagRules.ValidatePlan(p,Profile(),DateTimeOffset.UtcNow));}
    [Fact] public void StructuredAdviceMustBindEvidenceAndCannotInventResources(){var i=Inventory();var f=TagRules.Analyze(i,Profile())[0];var advice=new WorkflowReview("platform.agent-review/v1","tagging",i.Digest,"User input needed",[new("r1",Id,"custom.team","Example","AddIfAbsent",[f.Id],"Explicit user example")]);Assert.Single(WorkflowReviews.Tags(TagJson.Write(advice),i,Profile()).Recommendations);Assert.Throws<TagException>(()=>WorkflowReviews.Tags(TagJson.Write(advice with{EvidenceDigest="different"}),i,Profile()));Assert.Throws<TagException>(()=>WorkflowReviews.Tags(TagJson.Write(advice with{Recommendations=[advice.Recommendations[0] with{ResourceId=Id+"-invented"}]}),i,Profile()));Assert.Throws<TagException>(()=>WorkflowReviews.Tags(TagJson.Write(advice with{Recommendations=[advice.Recommendations[0] with{EvidenceRefs=["invented"]}]}),i,Profile()));}
    sealed class Arm : HttpMessageHandler
    {
        public Dictionary<string,string> Tags=new(){{"keep","unchanged"}};public int Writes;public bool UnknownWrite,Drift,Denied;
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage r,CancellationToken ct)
        {
            Assert.Equal("management.azure.com",r.RequestUri!.Host);object value;
            if(r.Method==HttpMethod.Patch){Writes++;using var body=JsonDocument.Parse(await r.Content!.ReadAsStringAsync(ct));Assert.Equal("Merge",body.RootElement.GetProperty("operation").GetString());foreach(var p in body.RootElement.GetProperty("properties").GetProperty("tags").EnumerateObject())Tags[p.Name]=p.Value.GetString()!;if(UnknownWrite)throw new HttpRequestException("ambiguous response");value=new{properties=new{tags=Tags}};}
            else if(r.RequestUri.AbsolutePath.EndsWith("tags/default")){if(Denied)return new(HttpStatusCode.Forbidden);value=new{properties=new{tags=Drift?new Dictionary<string,string>{{"changed","outside"}}:Tags}};}
            else if(r.RequestUri.AbsolutePath=="/subscriptions/"+Sub)value=new{tenantId=Tenant,state="Enabled"};
            else value=new{value=Array.Empty<object>()};
            return new(HttpStatusCode.OK){Content=new StringContent(JsonSerializer.Serialize(value),Encoding.UTF8,"application/json")};
        }
    }
    static AzureTags Client(Arm arm)=>new(new HttpClient(arm),ct=>Task.FromResult("fixture-token"));
    [Fact] public async Task ApplyUsesMergeAndVerifiesUnrelatedTags(){var h=new Arm();var a=Client(h);var p=Profile() with{Enabled=true,GovernanceReviewed=true,GovernanceDigest=await a.Governance(Profile(),default)};var i=TagRules.Seal(Inventory(p,h.Tags) with{GovernanceDigest=p.GovernanceDigest});var plan=await a.Preview(i,Request(i),p,default);var receipts=new List<TagReceipt>();var r=await a.Apply(plan,p,x=>{receipts.Add(x);return Task.CompletedTask;},default);Assert.Equal("Verified",r.State);Assert.Equal(1,h.Writes);Assert.Equal("unchanged",h.Tags["keep"]);Assert.Contains(receipts,x=>x.Results.Any(r=>r.State=="Pending"));}
    [Theory][InlineData(true,false)][InlineData(false,true)] public async Task DriftOrDisabledProfileProducesNoWrites(bool drift,bool disabled){var h=new Arm();var a=Client(h);var p=Profile() with{Enabled=!disabled,GovernanceReviewed=true,GovernanceDigest=await a.Governance(Profile(),default)};var i=TagRules.Seal(Inventory(p,h.Tags) with{GovernanceDigest=p.GovernanceDigest});var plan=TagRules.BuildPlan(i,Request(i),p,DateTimeOffset.UtcNow);h.Drift=drift;await Assert.ThrowsAsync<TagException>(()=>a.Apply(plan,p,_=>Task.CompletedTask,default));Assert.Equal(0,h.Writes);}
    [Fact] public async Task AmbiguousWriteRetainsReceiptAndNeverRetries(){var h=new Arm{UnknownWrite=true};var a=Client(h);var p=Profile() with{Enabled=true,GovernanceReviewed=true,GovernanceDigest=await a.Governance(Profile(),default)};var i=TagRules.Seal(Inventory(p,h.Tags) with{GovernanceDigest=p.GovernanceDigest});var plan=TagRules.BuildPlan(i,Request(i),p,DateTimeOffset.UtcNow);var r=await a.Apply(plan,p,_=>Task.CompletedTask,default);Assert.Equal("Incomplete",r.State);Assert.Equal("Unknown",r.Results[0].State);Assert.Equal(1,h.Writes);}
    [Fact] public async Task ForbiddenTagReadIsNotEmpty(){var h=new Arm{Denied=true};await Assert.ThrowsAsync<TagException>(()=>Client(h).ReadTags(Id,default));Assert.Equal(0,h.Writes);}
    [Fact] public async Task UnauthenticatedBrowserCannotReadAnotherSessionsEvidence(){var root=new DirectoryInfo(AppContext.BaseDirectory);while(root is not null&&!File.Exists(Path.Combine(root.FullName,"config/workloads.json")))root=root.Parent;var options=new PortalOptions{RepositoryRoot=root!.FullName};using var session=new BrowserSession(new());var service=new TaggingService(new HttpClient(),null!,new Catalog(options),options,null!);Assert.Throws<PortalException>(()=>service.Evidence(session,"fixture"));session.Connected["azure"]=true;Assert.Throws<PortalException>(()=>service.Evidence(session,"fixture"));await Task.CompletedTask;}
}
