#requires -Version 7.4
[CmdletBinding()]
param([switch]$Check,[string]$CatalogDirectory='',[string]$OutputRoot='')
. "$PSScriptRoot/self-service-common.ps1"
. "$PSScriptRoot/service-cost-common.ps1"
. "$PSScriptRoot/platform-contract.ps1"
# Bound each YAML expression key below YAML's 1024-character simple-key limit.
function New-CatalogRejection($Conditions,[string[]]$Body) {
    $lines=@();$indent='  '
    for($offset=0;$offset -lt $Conditions.Count;$offset+=3){
        $group=@($Conditions|Select-Object -Skip $offset -First 3)
        $match=if($group.Count -eq 1){$group[0]}else{'or('+($group -join ', ')+')'}
        $lines+=($indent+'- ${{ if not('+$match+') }}:');$indent+='  '
    }
    foreach($line in $Body){$lines+=($indent+$line.Substring(4))}
    return $lines
}
$prices=Read-ServicePrices
$logicPrices=Get-Content (Join-Path (Get-ProjectRoot) 'self-service/pricing/logic-app-eastus2.json') -Raw|ConvertFrom-Json -AsHashtable
$logicMonthly=Format-ServiceUsd (($logicPrices.rates.WS1+8*$logicPrices.rates.privateEndpoint)*730)
# Keep generated YAML identical on developer machines and UTC-hosted agents.
$priceDate=([DateTimeOffset]$prices.retrievedUtc).UtcDateTime.ToString('yyyy-MM-dd',[Globalization.CultureInfo]::InvariantCulture)
$endpointMonthly=[double]$prices.rates.privateEndpoint.retailPrice*730
$alertsMonthly=[double]$prices.rates.logAlert.retailPrice*3
$hosting=(@('B1','S1','P1v3') | ForEach-Object { "$_ $(Format-ServiceUsd ([double]$prices.rates[$_].retailPrice*730))" }) -join '; '
$settings=Get-Content (Join-Path (Get-ProjectRoot) 'self-service/pipeline-settings.json') -Raw | ConvertFrom-Json -AsHashtable
if ($settings.discoveryPipelineName -isnot [string] -or [string]::IsNullOrWhiteSpace($settings.discoveryPipelineName) -or $settings.discoveryPipelineName -match '[\r\n]' -or $settings.discoveryPipelineName.Contains('$')) { throw 'Configure the exact Azure DevOps discovery pipeline name in self-service/pipeline-settings.json.' }
$discoverySource=ConvertTo-Json -InputObject $settings.discoveryPipelineName -Compress
$root=if ($OutputRoot) { [IO.Path]::GetFullPath($OutputRoot) } else { Get-ProjectRoot }
if (!$CatalogDirectory) { $CatalogDirectory=Join-Path (Get-ProjectRoot) 'self-service/targets' }
$targets=@(Get-ChildItem $CatalogDirectory -Filter *.json | Sort-Object Name | ForEach-Object { Get-Content $_.FullName -Raw | ConvertFrom-Json -AsHashtable })
if (!$targets.Count) { throw 'No registered target profiles.' }
$selections=@{}; $aliases=@{}; $resourceOwners=@{}
foreach ($t in $targets) {
    if ($t.schemaVersion -notin @(2,3)) { throw 'Dropdown generation requires schemaVersion 2 or 3 target profiles.' }
    foreach ($key in @('workload','environmentName','subscriptionAlias','networkProfile')) { if ($t[$key] -cnotmatch '^[a-z0-9][a-z0-9-]{0,39}$') { throw "Invalid catalog key: $key" } }
    foreach ($key in @('serviceConnection','agentPool','deploymentEnvironment')) { if ($t[$key] -cnotmatch '^[a-zA-Z0-9][a-zA-Z0-9._-]{0,79}$') { throw "Invalid protected resource binding: $key" } }
    if ($t.subscriptionId -ne [guid]::Empty.ToString()) { Assert-ServiceTarget $t $t.workload $t.environmentName -AllowDisabled }
    elseif ($t.enabled -isnot [bool] -or $t.enabled) { throw 'A placeholder subscription cannot be enabled.' }
    $type=Get-TargetWorkloadType $t
    $null=Get-WorkloadDefinition $type
    foreach($resourceKey in @("$($t.subscriptionId)/rg/$($t.resourceGroup)","$($t.subscriptionId)/stack/$($t.workload)/$($t.environmentName)")) {
        if($resourceOwners.ContainsKey($resourceKey) -and $resourceOwners[$resourceKey] -cne "$type/$($t.workload)/$($t.environmentName)"){throw 'Workload resource ownership collision.'}
        $resourceOwners[$resourceKey]="$type/$($t.workload)/$($t.environmentName)"
    }
    $key="$($t.workload)/$($t.environmentName)/$($t.subscriptionAlias)/$($t.networkProfile)"
    if ($selections.ContainsKey($key)) { throw 'Duplicate subscription/network target selection.' }; $selections[$key]=$true
    if ($aliases.ContainsKey($t.subscriptionAlias) -and $aliases[$t.subscriptionAlias] -ine $t.subscriptionId) { throw 'One subscription alias cannot identify different subscription IDs.' }; $aliases[$t.subscriptionAlias]=$t.subscriptionId
}
$header=@('# Generated by scripts/Update-ServiceCatalog.ps1. Review catalog changes before merging.','trigger: none','pr: none')
$platform=Read-PlatformConfiguration
$stackConfiguration=Read-StackConfiguration
$intents=@(Get-PlatformIntentTargets $targets $platform)
$defaultTarget=$targets[0]
$choices=@('  - name: workloadType','    displayName: Approved workload pattern','    type: string',('    default: '+(Get-TargetWorkloadType $defaultTarget)),('    values: ['+((@($targets|ForEach-Object {Get-TargetWorkloadType $_}|Sort-Object -Unique)) -join ', ')+']'))
foreach ($pair in @(@('workload','workload','Registered workload (blobcopy = blob transfer; eventflow = Logic App events)'),@('environment','environmentName','Target environment'),@('subscription','subscriptionAlias','Approved subscription'),@('network','networkProfile','Registered network profile'))) {
    $values=@($targets | ForEach-Object { $_[$pair[1]] } | Sort-Object -Unique)
    $choices+=@("  - name: $($pair[0])","    displayName: $($pair[2])",'    type: string',"    default: $($defaultTarget[$pair[1]])",('    values: ['+($values -join ', ')+']'))
}
$yaml=$header+@('# Discover only. Publishes inventory; never provisions resources.','','parameters:')+$choices
foreach ($info in @(
    @('discoveryScope','What this run checks - read only','Lists networks, subnets and private DNS zones in the selected subscription, plus accessible matching ADO service connections. Logic App discovery also records provider registration and resource IDs/types. Empty results and failed reads are reported separately. No Azure resources or permissions are changed.'),
    @('deploymentHandoff','Next step - use the saved discovery in Deploy','For deployment, run discovery on main for the matching workload/environment. After success, open Deploy on main and select this run under Resources > discovery within seven days. Feature runs are diagnostic only. Discovery does not enable a target or prove deployment readiness.')
)) {
    $label=ConvertTo-Json -InputObject $info[1] -Compress
    $value=ConvertTo-Json -InputObject $info[2] -Compress
    $yaml+=@("  - name: $($info[0])","    displayName: $label",'    type: string',"    default: $value",'    values:',"      - $value")
}
$deploymentYaml=$header+@('# Developer intent only. Platform owns topology and security options.','','resources:','  pipelines:','    - pipeline: discovery',"      source: $discoverySource",'      branch: refs/heads/main','      trigger: none','','parameters:')
foreach ($pair in @(@('workloadType','Approved workload pattern'),@('workloadName','Registered workload'),@('environment','Environment'),@('region','Approved region'))) {
    $values=@($intents | ForEach-Object { $_.($pair[0]) } | Sort-Object -Unique)
    $deploymentYaml+=@("  - name: $($pair[0])","    displayName: $($pair[1])",'    type: string',"    default: $($intents[0].($pair[0]))",('    values: ['+($values -join ', ')+']'))
}
# Native Run pipeline forms support labels and allowed values, not rich help panels.
# Single-value fields describe this repository's common deployment blueprint.
# They are informational only and are never forwarded to scripts or templates.
foreach ($info in @(
    @('runGuidance','Before running - discovery, approvals and readiness','Use main. Under Resources > discovery, select a successful main run for the same workload/environment. Enabled targets publish the approved template, preview changes for approval, deploy and verify the application. Disabled targets run setup checks only.'),
    @('packageResources','Included core resources (required)','blob-transfer: Function App, 2 Storage accounts, queues, ledger, identity, monitoring. logic-app-event-grid: Logic App Standard, Event Grid topic/subscription, 2 Storage accounts, receipt/quarantine/dead-letter storage, 8 private endpoints, identity and monitoring.'),
    @('hostingEstimate',"Hosting reference - USD per instance/month (East US 2; $priceDate)","Blob-transfer: $hosting. Logic App WS1 + 8 endpoints: $logicMonthly/month plus usage (USD East US 2, $(([DateTimeOffset]$logicPrices.retrievedUtc).UtcDateTime.ToString('yyyy-MM-dd'))). Multiply by profile instance count; exact selected subtotal is published during qualification."),
    @('packageNetworking','Platform-managed private access',"Private access, endpoints, DNS and routing follow the approved platform profile. Blob-transfer reference: 6 core endpoints $(Format-ServiceUsd ($endpointMonthly*6))/month; destination adds up to $(Format-ServiceUsd ($endpointMonthly*2))/month. Logic App has 8 endpoints already included in its hosting reference above. Shared networking remains separately billable."),
    @('usageEstimate','Additional usage charges - not included in fixed amounts',"Storage capacity/transactions, endpoint data, egress, notifications and agent costs vary. Logs: $(Format-ServiceUsd $prices.rates.logIngestion.retailPrice)/GB at paid tier; DNS queries: $(Format-ServiceUsd $prices.rates.privateDnsQueries.retailPrice)/million. Allowances depend on subscription usage."),
    @('packageRequirements',"Requirements / USD retail as of $priceDate", "Platform owns connection, destination, agent, network and alert settings. Blob-transfer: 3 log alert rules ~$alertsMonthly/month plus usage. Logic App: 5 alert rules; alert costs are additional. Prices: East US 2, 730 hours/month, excluding tax/discounts/credits. Not a spending cap. Disabled targets run setup only.")
)) {
    $label=ConvertTo-Json -InputObject $info[1] -Compress
    $value=ConvertTo-Json -InputObject $info[2] -Compress
    $deploymentYaml+=@("  - name: $($info[0])","    displayName: $label",'    type: string',"    default: $value",'    values:',"      - $value")
}
# Operation is fixed by each entry point; source run IDs come from native resource metadata.
# Macro strings resolve in task inputs/environment at runtime, not template conditions.
$tail=@('','stages:','  - template: pipelines/catalog-bindings.yml','    parameters:','      workloadType: ${{ parameters.workloadType }}','      workload: ${{ parameters.workload }}','      environment: ${{ parameters.environment }}','      subscription: ${{ parameters.subscription }}','      network: ${{ parameters.network }}')
$yaml+=$tail+@('      operation: discover')
$deploymentYaml+=@('','extends:','  template: pipelines/deploy-entry.yml','  parameters:','    workloadType: ${{ parameters.workloadType }}','    workloadName: ${{ parameters.workloadName }}','    environment: ${{ parameters.environment }}','    region: ${{ parameters.region }}','    discoveryPipelineId: $(resources.pipeline.discovery.pipelineID)','    discoveryRunId: $(resources.pipeline.discovery.runID)')
$deployEntry=@('# Generated platform-owned entry template. Protect this file and its generator.','parameters:')
foreach($key in @('workloadType','workloadName','environment','region','discoveryPipelineId','discoveryRunId')) { $deployEntry+=@("  - name: $key",'    type: string') }
$deployEntry+=@('stages:')
$intentConditions=@()
foreach ($intent in $intents) {
    $condition='and(eq(parameters.workloadName, '''+$intent.workloadName+'''), eq(parameters.environment, '''+$intent.environment+'''), eq(parameters.region, '''+$intent.region+'''), eq(parameters.workloadType, '''+$intent.workloadType+'''))'
    $intentConditions+=$condition
    $t=$intent.target
    $deployEntry+=@(('  - ${{ if '+$condition+' }}:'),'    - template: catalog-bindings.yml','      parameters:',"        workloadType: $($intent.workloadType)","        workload: $($t.workload)","        environment: $($t.environmentName)","        subscription: $($t.subscriptionAlias)","        network: $($t.networkProfile)",'        operation: deploy','        discoveryPipelineId: ${{ parameters.discoveryPipelineId }}','        discoveryRunId: ${{ parameters.discoveryRunId }}',"        createDestinationPrivateEndpoints: $($platform.createDestinationPrivateEndpoints.ToString().ToLowerInvariant())","        enableLogAlerts: $($platform.enableLogAlerts.ToString().ToLowerInvariant())")
}
$deployEntry+=@(New-CatalogRejection $intentConditions @('    - stage: InvalidIntent','      jobs:','        - job: RejectIntent','          pool:','            vmImage: windows-latest','          steps:','            - checkout: none',"            - pwsh: throw 'Unregistered workload request. Contact the platform team.'"))
$bindings=@('# Generated stage routing with literal protected-resource parameters.','parameters:')
foreach ($key in @('operation','workload','environment','subscription','network')) { $bindings+=@("  - name: $key",'    type: string') }
foreach ($key in @('discoveryPipelineId','discoveryRunId')) { $bindings+=@("  - name: $key",'    type: string',"    default: '0'") }
foreach ($key in @('createDestinationPrivateEndpoints','enableLogAlerts')) { $bindings+=@("  - name: $key",'    type: boolean','    default: true') }
$bindings+=@('  - name: workloadType','    type: string',"    default: 'blob-transfer'",'stages:')
$conditions=@()
foreach ($t in $targets) {
    $condition='and(eq(parameters.workloadType, '''+(Get-TargetWorkloadType $t)+'''), eq(parameters.workload, '''+$t.workload+'''), eq(parameters.environment, '''+$t.environmentName+'''), eq(parameters.subscription, '''+$t.subscriptionAlias+'''), eq(parameters.network, '''+$t.networkProfile+'''))'
    $conditions+=$condition
    $bindings+=('  - ${{ if '+$condition+' }}:')
    foreach ($op in @('discover','deploy')) {
        # Omit private-pool/environment jobs entirely for disabled targets. A runtime
        # condition would still let ADO validate their missing resources at queue time.
        $template=if ($op -eq 'discover') {'self-service-discover'} elseif (!$t.enabled) {'self-service-setup'} else {'self-service-stages'}
        $bindings+=@(('    - ${{ if eq(parameters.operation, '''+$op+''') }}:'),"      - template: templates/$template.yml",'        parameters:',
            "          workload: $($t.workload)","          environment: $($t.environmentName)","          subscription: $($t.subscriptionAlias)","          network: $($t.networkProfile)",
            "          serviceConnection: $($t.serviceConnection)")
        if ($op -eq 'deploy') {
            if ($t.enabled) { $bindings+=@("          workloadType: $(Get-TargetWorkloadType $t)","          agentPool: $($t.agentPool)","          deploymentEnvironment: $($t.deploymentEnvironment)") }
            if ($t.enabled) { foreach($key in @('publisherServiceConnection','publisherEnvironment','publisherAgentPool')) { $bindings+="          ${key}: $($stackConfiguration.templateSpec[$key])" } }
            $bindings+=@('          discoveryPipelineId: ${{ parameters.discoveryPipelineId }}','          discoveryRunId: ${{ parameters.discoveryRunId }}','          createDestinationPrivateEndpoints: ${{ parameters.createDestinationPrivateEndpoints }}','          enableLogAlerts: ${{ parameters.enableLogAlerts }}')
        }
    }
}
$bindings+=@(New-CatalogRejection $conditions @('    - stage: InvalidSelection','      jobs:','        - job: RejectSelection','          pool:','            vmImage: windows-latest','          steps:','            - checkout: none','            - pwsh: |','                throw ''This workload/environment/subscription/network combination is not registered.''','              displayName: Reject unregistered target before Azure access'))
foreach ($item in @(@('azure-pipelines-self-service.yml',$yaml),@('azure-pipelines-self-service-deploy.yml',$deploymentYaml),@('pipelines/catalog-bindings.yml',$bindings),@('pipelines/deploy-entry.yml',$deployEntry))) {
    $path=Join-Path $root $item[0]; $text=($item[1] -join "`n")+"`n"
    if ($Check) {
        if (!(Test-Path $path) -or ([IO.File]::ReadAllText($path).Replace("`r`n","`n")) -cne $text) { throw "Generated catalog is stale: $($item[0]). Run Update-ServiceCatalog.ps1." }
    } else { New-Item -ItemType Directory -Path (Split-Path -Parent $path) -Force | Out-Null; [IO.File]::WriteAllText($path,$text,[Text.UTF8Encoding]::new($false)) }
}
Write-Host "PASS: catalog has $($targets.Count) unique registered target selections."
