#requires -Version 7.4
[CmdletBinding()]
param([switch]$Check,[string]$CatalogDirectory='',[string]$OutputRoot='')
. "$PSScriptRoot/self-service-common.ps1"
. "$PSScriptRoot/service-cost-common.ps1"
. "$PSScriptRoot/platform-contract.ps1"
# Bound each YAML expression key below YAML's 1024-character simple-key limit.
function New-CatalogRejection($Conditions,[string[]]$Body) {
    $lines=@();$indent='  '
    for($offset=0;$offset -lt $Conditions.Count;$offset+=3){
        $group=@($Conditions|Select-Object -Skip $offset -First 3)
        $match=if($group.Count -eq 1){$group[0]}else{'or('+($group -join ', ')+')'}
        $lines+=($indent+'- ${{ if not('+$match+') }}:');$indent+='  '
    }
    foreach($line in $Body){$lines+=($indent+$line.Substring(4))}
    return $lines
}
$prices=Read-ServicePrices
$logicPrices=Get-Content (Join-Path (Get-ProjectRoot) 'self-service/pricing/logic-app-eastus2.json') -Raw|ConvertFrom-Json -AsHashtable
$logicMonthly=Format-ServiceUsd (($logicPrices.rates.WS1+8*$logicPrices.rates.privateEndpoint)*730)
# Keep generated YAML identical on developer machines and UTC-hosted agents.
$priceDate=([DateTimeOffset]$prices.retrievedUtc).UtcDateTime.ToString('yyyy-MM-dd',[Globalization.CultureInfo]::InvariantCulture)
$endpointMonthly=[double]$prices.rates.privateEndpoint.retailPrice*730
$alertsMonthly=[double]$prices.rates.logAlert.retailPrice*3
$hosting=(@('B1','S1','P1v3') | ForEach-Object { "$_ $(Format-ServiceUsd ([double]$prices.rates[$_].retailPrice*730))" }) -join '; '
$settings=Get-Content (Join-Path (Get-ProjectRoot) 'self-service/pipeline-settings.json') -Raw | ConvertFrom-Json -AsHashtable
if ($settings.discoveryPipelineName -isnot [string] -or [string]::IsNullOrWhiteSpace($settings.discoveryPipelineName) -or $settings.discoveryPipelineName -match '[\r\n]' -or $settings.discoveryPipelineName.Contains('$')) { throw 'Configure the exact Azure DevOps discovery pipeline name in self-service/pipeline-settings.json.' }
$discoverySource=ConvertTo-Json -InputObject $settings.discoveryPipelineName -Compress
$root=if ($OutputRoot) { [IO.Path]::GetFullPath($OutputRoot) } else { Get-ProjectRoot }
if (!$CatalogDirectory) { $CatalogDirectory=Join-Path (Get-ProjectRoot) 'self-service/targets' }
$targets=@(Get-ChildItem $CatalogDirectory -Filter *.json | Sort-Object Name | ForEach-Object { Get-Content $_.FullName -Raw | ConvertFrom-Json -AsHashtable })
if (!$targets.Count) { throw 'No registered target profiles.' }
$selections=@{}; $aliases=@{}; $resourceOwners=@{}
foreach ($t in $targets) {
    if ($t.schemaVersion -notin @(2,3)) { throw 'Dropdown generation requires schemaVersion 2 or 3 target profiles.' }
    foreach ($key in @('workload','environmentName','subscriptionAlias','networkProfile')) { if ($t[$key] -cnotmatch '^[a-z0-9][a-z0-9-]{0,39}$') { throw "Invalid catalog key: $key" } }
    foreach ($key in @('serviceConnection','agentPool','deploymentEnvironment')) { if ($t[$key] -cnotmatch '^[a-zA-Z0-9][a-zA-Z0-9._-]{0,79}$') { throw "Invalid protected resource binding: $key" } }
    if ($t.subscriptionId -ne [guid]::Empty.ToString()) { Assert-ServiceTarget $t $t.workload $t.environmentName -AllowDisabled }
    elseif ($t.enabled -isnot [bool] -or $t.enabled) { throw 'A placeholder subscription cannot be enabled.' }
    $type=Get-TargetWorkloadType $t
    $null=Get-WorkloadDefinition $type
    foreach($resourceKey in @("$($t.subscriptionId)/rg/$($t.resourceGroup)","$($t.subscriptionId)/stack/$($t.workload)/$($t.environmentName)")) {
        if($resourceOwners.ContainsKey($resourceKey) -and $resourceOwners[$resourceKey] -cne "$type/$($t.workload)/$($t.environmentName)"){throw 'Workload resource ownership collision.'}
        $resourceOwners[$resourceKey]="$type/$($t.workload)/$($t.environmentName)"
    }
    $key="$($t.workload)/$($t.environmentName)/$($t.subscriptionAlias)/$($t.networkProfile)"
    if ($selections.ContainsKey($key)) { throw 'Duplicate subscription/network target selection.' }; $selections[$key]=$true
    if ($aliases.ContainsKey($t.subscriptionAlias) -and $aliases[$t.subscriptionAlias] -ine $t.subscriptionId) { throw 'One subscription alias cannot identify different subscription IDs.' }; $aliases[$t.subscriptionAlias]=$t.subscriptionId
}
$header=@('# Generated by scripts/Update-ServiceCatalog.ps1. Review catalog changes before merging.','trigger: none','pr: none')
$platform=Read-PlatformConfiguration
$stackConfiguration=Read-StackConfiguration
$intents=@(Get-PlatformIntentTargets $targets $platform)
# Human-readable root choices map back to canonical IDs before protected routing.
# Keep the separator and mapping explicit; explanatory text never reaches scripts.
$menuLabels=@{
    'blob-transfer'='Blob copy - Function App + 2 Storage accounts | blob-transfer'
    'logic-app-event-grid'='Event flow - Logic App + Event Grid + 2 Storage accounts | logic-app-event-grid'
}
$blueprints=@{
    'blob-transfer'='Copies uploaded files to an existing data lake: 1 Function App + hosting plan, 2 Storage accounts, work/poison queues, transfer ledger, managed identity, Application Insights and alerts. Private endpoints and DNS follow the approved environment profile.'
    'logic-app-event-grid'='Processes document events: 1 Logic App Standard + hosting plan, 1 Event Grid topic + subscription, 2 Storage accounts, events queue, receipt/quarantine/dead-letter containers, 8 private endpoints, managed identities, Application Insights and 5 alerts.'
}
$defaultTarget=$targets[0]
$choices=@('  - name: workloadType','    displayName: "1. What do you want to prepare? (Discover creates no Azure resources)"','    type: string',('    default: '+(ConvertTo-Json -InputObject $menuLabels[(Get-TargetWorkloadType $defaultTarget)] -Compress)),'    values:')
foreach($type in @($targets|ForEach-Object {Get-TargetWorkloadType $_}|Sort-Object -Unique)){$choices+=('      - '+(ConvertTo-Json -InputObject $menuLabels[$type] -Compress))}
foreach ($pair in @(@('workload','workload','2. Instance name (Blob copy = blobcopy; Event flow = eventflow)'),@('environment','environmentName','Target environment'),@('subscription','subscriptionAlias','Approved subscription'),@('network','networkProfile','Registered network profile'))) {
    $values=@($targets | ForEach-Object { $_[$pair[1]] } | Sort-Object -Unique)
    $choices+=@("  - name: $($pair[0])","    displayName: $($pair[2])",'    type: string',"    default: $($defaultTarget[$pair[1]])",('    values: ['+($values -join ', ')+']'))
}
$yaml=$header+@('# Discover only. Publishes inventory; never provisions resources.','','parameters:')+$choices
$discoverInfo=@(
    @('blobTransferBlueprint','Blob copy / blobcopy - what a later Deploy creates',$blueprints['blob-transfer']),
    @('eventFlowBlueprint','Event flow / eventflow - what a later Deploy creates',$blueprints['logic-app-event-grid']),
    @('discoveryScope','What this run checks - read only','Lists networks, subnets and private DNS zones in the selected subscription, plus accessible matching ADO service connections. Logic App discovery also records provider registration and resource IDs/types. Empty results and failed reads are reported separately. No Azure resources or permissions are changed.'),
    @('deploymentHandoff','Next step - use the saved discovery in Deploy','For deployment, run discovery on main for the matching workload/environment. After success, open Deploy on main and select this run under Resources > discovery within seven days. Feature runs are diagnostic only. Discovery does not enable a target or prove deployment readiness.')
)
foreach ($info in @($discoverInfo|Where-Object {$_[0] -notin @('blobTransferBlueprint','eventFlowBlueprint')})) {
    $label=ConvertTo-Json -InputObject $info[1] -Compress
    $value=ConvertTo-Json -InputObject $info[2] -Compress
    $yaml+=@("  - name: $($info[0])","    displayName: $label",'    type: string',"    default: $value",'    values:',"      - $value")
}
$deploymentYaml=$header+@('# Developer intent only. Platform owns topology and security options.','','resources:','  pipelines:','    - pipeline: discovery',"      source: $discoverySource",'      branch: refs/heads/main','      trigger: none','','parameters:')
foreach ($pair in @(@('workloadType','1. What do you want to deploy?'),@('workloadName','2. Instance name (Blob copy = blobcopy; Event flow = eventflow)'),@('environment','3. Environment'),@('region','4. Approved region'))) {
    $values=@($intents | ForEach-Object { $_.($pair[0]) } | Sort-Object -Unique)
    $default=$intents[0].($pair[0])
    if($pair[0] -eq 'workloadType'){$values=@($values|ForEach-Object {$menuLabels[$_]});$default=$menuLabels[$default]}
    $deploymentYaml+=@("  - name: $($pair[0])",('    displayName: '+(ConvertTo-Json -InputObject $pair[1] -Compress)),'    type: string',('    default: '+(ConvertTo-Json -InputObject $default -Compress)),'    values:')
    foreach($value in $values){$deploymentYaml+=('      - '+(ConvertTo-Json -InputObject $value -Compress))}
}
$enabledCount=@($targets|Where-Object {$_.enabled}).Count
$catalogStatus=if($enabledCount -eq 0){'All checked-in targets are disabled: Deploy currently creates NO Azure resources.'}else{"$enabledCount of $($targets.Count) targets are enabled; disabled targets run setup checks and create NO Azure resources."}
# Native forms cannot provide dependent help panels. Give each pattern its own
# static create/reuse/cost fields, clearly marked as reference information.
# These single-value fields never flow into infrastructure parameters.
$deployInfo=@(
    @('runGuidance','Current behavior - deployment depends on target enablement',"$catalogStatus Once enabled, it creates the selected workload in its own resource group and Deployment Stack, publishes/reuses a Template Spec, and verifies the application. Use main and choose matching Resources > discovery."),
    @('blobTransferCreates','BLOB COPY / blobcopy - creates (reference only)',$blueprints['blob-transfer']),
    @('blobTransferRequirements','BLOB COPY / blobcopy - existing dependencies and cost',"Requires an existing destination data lake/container and approved network/monitoring profile. Network/DNS/workspace may be reused or created only as permitted by that profile. Hosting: $hosting per instance/month; 6 core endpoints $(Format-ServiceUsd ($endpointMonthly*6))/month, up to 2 destination endpoints extra. 3 log alerts ~$alertsMonthly/month. Usage extra."),
    @('eventFlowCreates','EVENT FLOW / eventflow - creates (reference only)',$blueprints['logic-app-event-grid']),
    @('eventFlowRequirements','EVENT FLOW / eventflow - existing dependencies and cost',"Requires 2 existing subnets, 6 linked private DNS zones, a Log Analytics workspace, private agent and 2 platform exception approvals. Creates NO shared VNet/DNS/workspace or destination data lake. WS1 + 8 endpoints: $logicMonthly/month fixed subtotal; usage and 5 alerts extra."),
    @('usageEstimate',"Cost assumptions - USD East US 2 retail as of $priceDate",'References assume 730 hours/month, excluding tax/discounts/credits. Storage, Event Grid operations, logs, DNS, data transfer and agents cost extra. Exact selected estimate is frozen during qualification. Estimates are not spending caps. For workload-specific resource and dependency summaries, use the dedicated Blob copy or Event flow pipeline menu.')
)
foreach ($info in @($deployInfo|Where-Object {$_[0] -in @('runGuidance','usageEstimate')})) {
    $label=ConvertTo-Json -InputObject $info[1] -Compress
    $value=ConvertTo-Json -InputObject $info[2] -Compress
    $deploymentYaml+=@("  - name: $($info[0])","    displayName: $label",'    type: string',"    default: $value",'    values:',"      - $value")
}
# Operation is fixed by each entry point; source run IDs come from native resource metadata.
# Macro strings resolve in task inputs/environment at runtime, not template conditions.
$tail=@('','stages:','  - template: pipelines/catalog-bindings.yml','    parameters:',"      workloadType: `${{ split(parameters.workloadType, ' | ')[1] }}",'      workload: ${{ parameters.workload }}','      environment: ${{ parameters.environment }}','      subscription: ${{ parameters.subscription }}','      network: ${{ parameters.network }}')
$yaml+=$tail+@('      operation: discover')
$deploymentYaml+=@('','extends:','  template: pipelines/deploy-entry.yml','  parameters:',"    workloadType: `${{ split(parameters.workloadType, ' | ')[1] }}",'    workloadName: ${{ parameters.workloadName }}','    environment: ${{ parameters.environment }}','    region: ${{ parameters.region }}','    discoveryPipelineId: $(resources.pipeline.discovery.pipelineID)','    discoveryRunId: $(resources.pipeline.discovery.runID)')
$deployEntry=@('# Generated platform-owned entry template. Protect this file and its generator.','parameters:')
foreach($key in @('workloadType','workloadName','environment','region','discoveryPipelineId','discoveryRunId')) { $deployEntry+=@("  - name: $key",'    type: string') }
$deployEntry+=@('stages:')
$intentConditions=@()
foreach ($intent in $intents) {
    $condition='and(eq(parameters.workloadName, '''+$intent.workloadName+'''), eq(parameters.environment, '''+$intent.environment+'''), eq(parameters.region, '''+$intent.region+'''), eq(parameters.workloadType, '''+$intent.workloadType+'''))'
    $intentConditions+=$condition
    $t=$intent.target
    $deployEntry+=@(('  - ${{ if '+$condition+' }}:'),'    - template: catalog-bindings.yml','      parameters:',"        workloadType: $($intent.workloadType)","        workload: $($t.workload)","        environment: $($t.environmentName)","        subscription: $($t.subscriptionAlias)","        network: $($t.networkProfile)",'        operation: deploy','        discoveryPipelineId: ${{ parameters.discoveryPipelineId }}','        discoveryRunId: ${{ parameters.discoveryRunId }}',"        createDestinationPrivateEndpoints: $($platform.createDestinationPrivateEndpoints.ToString().ToLowerInvariant())","        enableLogAlerts: $($platform.enableLogAlerts.ToString().ToLowerInvariant())")
}
$deployEntry+=@(New-CatalogRejection $intentConditions @('    - stage: InvalidIntent','      jobs:','        - job: RejectIntent','          pool:','            vmImage: windows-latest','          steps:','            - checkout: none',"            - pwsh: throw 'Unregistered workload request. Contact the platform team.'"))
$bindings=@('# Generated stage routing with literal protected-resource parameters.','parameters:')
foreach ($key in @('operation','workload','environment','subscription','network')) { $bindings+=@("  - name: $key",'    type: string') }
foreach ($key in @('discoveryPipelineId','discoveryRunId')) { $bindings+=@("  - name: $key",'    type: string',"    default: '0'") }
foreach ($key in @('createDestinationPrivateEndpoints','enableLogAlerts')) { $bindings+=@("  - name: $key",'    type: boolean','    default: true') }
$bindings+=@('  - name: workloadType','    type: string',"    default: 'blob-transfer'",'stages:')
$conditions=@()
foreach ($t in $targets) {
    $condition='and(eq(parameters.workloadType, '''+(Get-TargetWorkloadType $t)+'''), eq(parameters.workload, '''+$t.workload+'''), eq(parameters.environment, '''+$t.environmentName+'''), eq(parameters.subscription, '''+$t.subscriptionAlias+'''), eq(parameters.network, '''+$t.networkProfile+'''))'
    $conditions+=$condition
    $bindings+=('  - ${{ if '+$condition+' }}:')
    foreach ($op in @('discover','deploy')) {
        # Omit private-pool/environment jobs entirely for disabled targets. A runtime
        # condition would still let ADO validate their missing resources at queue time.
        $template=if ($op -eq 'discover') {'self-service-discover'} elseif (!$t.enabled) {'self-service-setup'} else {'self-service-stages'}
        $bindings+=@(('    - ${{ if eq(parameters.operation, '''+$op+''') }}:'),"      - template: templates/$template.yml",'        parameters:',
            "          workload: $($t.workload)","          environment: $($t.environmentName)","          subscription: $($t.subscriptionAlias)","          network: $($t.networkProfile)",
            "          serviceConnection: $($t.serviceConnection)")
        if ($op -eq 'deploy') {
            if ($t.enabled) { $bindings+=@("          workloadType: $(Get-TargetWorkloadType $t)","          agentPool: $($t.agentPool)","          deploymentEnvironment: $($t.deploymentEnvironment)") }
            if ($t.enabled) { foreach($key in @('publisherServiceConnection','publisherEnvironment','publisherAgentPool')) { $bindings+="          ${key}: $($stackConfiguration.templateSpec[$key])" } }
            $bindings+=@('          discoveryPipelineId: ${{ parameters.discoveryPipelineId }}','          discoveryRunId: ${{ parameters.discoveryRunId }}','          createDestinationPrivateEndpoints: ${{ parameters.createDestinationPrivateEndpoints }}','          enableLogAlerts: ${{ parameters.enableLogAlerts }}')
        }
    }
}
$bindings+=@(New-CatalogRejection $conditions @('    - stage: InvalidSelection','      jobs:','        - job: RejectSelection','          pool:','            vmImage: windows-latest','          steps:','            - checkout: none','            - pwsh: |','                throw ''This workload/environment/subscription/network combination is not registered.''','              displayName: Reject unregistered target before Azure access'))
# Workload-specific native forms: select the ADO definition first. The workload
# is a literal protected-template argument, never a second dropdown or UI condition.
function New-MenuField([string]$Name,[string]$Label,[string]$Default,[string[]]$Values) {
    $lines=@("  - name: $Name",('    displayName: '+(ConvertTo-Json -InputObject $Label -Compress)),'    type: string',('    default: '+(ConvertTo-Json -InputObject $Default -Compress)),'    values:')
    foreach($value in $Values){$lines+=('      - '+(ConvertTo-Json -InputObject $value -Compress))}
    return $lines
}
$workloadMenus=@()
$discoveryNames=@{}
foreach($type in @($targets|ForEach-Object {Get-TargetWorkloadType $_}|Sort-Object -Unique)) {
    if(!$settings.workloadDiscoveryPipelineNames -or !$settings.workloadDiscoveryPipelineNames.Contains($type)){throw "Configure workloadDiscoveryPipelineNames for $type."}
    $sourceName=$settings.workloadDiscoveryPipelineNames[$type]
    if($sourceName -isnot [string] -or [string]::IsNullOrWhiteSpace($sourceName) -or $sourceName -match '[\r\n$]'){throw 'Invalid workload discovery pipeline name.'}
    if($discoveryNames.ContainsKey($sourceName) -or $sourceName -ieq $settings.discoveryPipelineName){throw 'Each workload discovery definition must have its own name, distinct from the generic definition.'}
    $discoveryNames[$sourceName]=$true
    $slug=if($type -eq 'blob-transfer'){'blobcopy'}else{'eventflow'}
    $title=if($type -eq 'blob-transfer'){'Blob copy'}else{'Event flow'}
    $profiles=@($targets|Where-Object {(Get-TargetWorkloadType $_) -ceq $type})
    $requests=@($intents|Where-Object {$_.workloadType -ceq $type})
    $sourceLiteral=ConvertTo-Json -InputObject $sourceName -Compress
    $discover=$header+@("# ADO definition: $sourceName. Fixed workload: $type.",'','parameters:')
    foreach($pair in @(@('workload','workload','Instance'),@('environment','environmentName','Environment'),@('subscription','subscriptionAlias','Approved subscription'),@('network','networkProfile','Approved network profile'))){
        $choices=@($profiles|ForEach-Object {$_[$pair[1]]}|Sort-Object -Unique)
        $discover+=New-MenuField $pair[0] $pair[2] $profiles[0][$pair[1]] $choices
    }
    $scope='Read-only networks, subnets, private DNS and accessible matching service connections. Creates no Azure resources.'
    if($type -eq 'logic-app-event-grid'){$scope+=' Also checks provider registration and resource IDs/types.'}
    foreach($info in @(@('workloadSummary',"$title - what a later deployment creates",$blueprints[$type]),@('discoveryScope','This run - discovery only',$scope),@('deploymentHandoff','Next step',"After successful main discovery, open Deploy - $title. Under Resources > discovery select this run. Use the same instance/environment; the artifact must be at most seven days old."))){
        $discover+=New-MenuField $info[0] $info[1] $info[2] @($info[2])
    }
    $discover+=@('','stages:','  - template: pipelines/catalog-bindings.yml','    parameters:',"      workloadType: $type",'      workload: ${{ parameters.workload }}','      environment: ${{ parameters.environment }}','      subscription: ${{ parameters.subscription }}','      network: ${{ parameters.network }}','      operation: discover')
    $deploy=$header+@("# ADO definition: Deploy - $title. Fixed workload: $type.",'','resources:','  pipelines:','    - pipeline: discovery',"      source: $sourceLiteral",'      branch: refs/heads/main','      trigger: none','','parameters:')
    foreach($pair in @(@('workloadName','Instance'),@('environment','Environment'),@('region','Approved region'))){
        $choices=@($requests|ForEach-Object {$_.($pair[0])}|Sort-Object -Unique)
        $deploy+=New-MenuField $pair[0] $pair[1] $requests[0].($pair[0]) $choices
    }
    $enabled=@($profiles|Where-Object {$_.enabled}).Count
    $status=if(!$enabled){"All $title targets are disabled: this run creates NO Azure resources; hosted setup checks only."}else{"$enabled of $($profiles.Count) $title targets are enabled. Disabled targets run setup checks only."}
    $requirementsKey=if($type -eq 'blob-transfer'){'blobTransferRequirements'}else{'eventFlowRequirements'}
    $requirements=@($deployInfo|Where-Object {$_[0] -eq $requirementsKey})[0][2]
    $ownDate=if($type -eq 'blob-transfer'){$priceDate}else{([DateTimeOffset]$logicPrices.retrievedUtc).UtcDateTime.ToString('yyyy-MM-dd',[Globalization.CultureInfo]::InvariantCulture)}
    $costText='USD East US 2 retail, 730 hours/month; tax, discounts and credits excluded. Storage, logs, DNS, network transfer and agents are additional. Qualification freezes the selected estimate; this is not a spending cap.'
    if($type -eq 'logic-app-event-grid'){$costText+=' Event Grid operations and alerts are also additional.'}
    foreach($info in @(@('runGuidance','Current target status',$status),@('workloadSummary',"$title - resources created when enabled",$blueprints[$type]),@('requirements','Existing dependencies and cost',$requirements),@('lifecycle','Deployment and discovery handoff',"Select a successful main run from $sourceName under Resources > discovery. Enabled deployment uses a dedicated resource group and Deployment Stack, a versioned Template Spec, approvals and application verification."),@('costAssumptions',"Cost assumptions - retail as of $ownDate",$costText))){
        $deploy+=New-MenuField $info[0] $info[1] $info[2] @($info[2])
    }
    $deploy+=@('','extends:','  template: pipelines/deploy-entry.yml','  parameters:',"    workloadType: $type",'    workloadName: ${{ parameters.workloadName }}','    environment: ${{ parameters.environment }}','    region: ${{ parameters.region }}','    discoveryPipelineId: $(resources.pipeline.discovery.pipelineID)','    discoveryRunId: $(resources.pipeline.discovery.runID)')
    $workloadMenus+=,@("azure-pipelines-$slug-discover.yml",$discover)
    $workloadMenus+=,@("azure-pipelines-$slug-deploy.yml",$deploy)
}
$generatedFiles=@(@('azure-pipelines-self-service.yml',$yaml),@('azure-pipelines-self-service-deploy.yml',$deploymentYaml),@('pipelines/catalog-bindings.yml',$bindings),@('pipelines/deploy-entry.yml',$deployEntry))+$workloadMenus
foreach ($item in $generatedFiles) {
    $path=Join-Path $root $item[0]; $text=($item[1] -join "`n")+"`n"
    if ($Check) {
        if (!(Test-Path $path) -or ([IO.File]::ReadAllText($path).Replace("`r`n","`n")) -cne $text) { throw "Generated catalog is stale: $($item[0]). Run Update-ServiceCatalog.ps1." }
    } else { New-Item -ItemType Directory -Path (Split-Path -Parent $path) -Force | Out-Null; [IO.File]::WriteAllText($path,$text,[Text.UTF8Encoding]::new($false)) }
}
Write-Host "PASS: catalog has $($targets.Count) unique registered target selections."
